# https://golangci-lint.run/usage/configuration/
# https://github.com/golangci/golangci-lint/blob/master/pkg/config/linters_settings.go
---
run:
  timeout: 1m
  issues-exit-code: 1
  tests: true
  skip-dirs: []
  skip-dirs-use-default: true
  skip-files: []
  allow-parallel-runners: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false
  sort-results: true

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: false
  dupl:
    threshold: 150
  errcheck:
    check-type-assertions: true
    check-blank: true
    # exclude: .errcheckignore
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  funlen:
    lines: 100
    statements: 60
  gocognit:
    min-complexity: 30
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - whyNoLint
    settings:
      hugeParam:
        sizeThreshold: 80
      rangeExprCopy:
        sizeThreshold: 512
      rangeValCopy:
        sizeThreshold: 128
  gocyclo:
    min-complexity: 30
  godot:
    scope: declarations
    capital: false
  gofmt:
    simplify: true
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/
  gosimple:
    go: "1.17"
  govet:
    enable-all: true
    check-shadowing: true
    disable:
      - fieldalignment
  importas:
    alias: []
    no-unaliased: true
  lll:
    line-length: 120
    tab-width: 1
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  nestif:
    min-complexity: 4
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  staticcheck:
    go: "1.17"
  testpackage:
    skip-regexp: '.*(export)_test\.go'
  unparam:
    check-exported: true
    algo: cha
  unused:
    go: "1.17"
  varnamelen:
    max-distance: 5
    min-name-length: 1
    check-receiver: true
    check-return: true
    ignore-type-assert-ok: false
    ignore-map-index-ok: false
    ignore-chan-recv-ok: false
  whitespace:
    multi-if: true
    multi-func: true

linters:
  fast: false
  disabled:
    - exhaustivestruct         # Checks if all struct's fields are initialized
    - forbidigo                # Forbids identifiers
    - forcetypeassert          # finds forced type assertions
    - gci                      # Gci control golang package import order and make it always deterministic.
    - gochecknoglobals         # check that no global variables exist
    - gochecknoinits           # Checks that no init functions are present in Go code
    - godox                    # Tool for detection of FIXME, TODO and other comment keywords
    - goerr113                 # Golang linter to check the errors handling expressions
    - goheader                 # Checks is file header matches to pattern
    - golint                   # Deprecated] Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes
    - gomnd                    # An analyzer to detect magic numbers.
    - gomoddirectives          # Manage the use of 'replace', 'retract', and 'excludes' directives in go.mod.
    - interfacer               # Deprecated: Linter that suggests narrower interface types
    - maligned                 # Deprecated: Tool to detect Go structs that would take less memory if their fields were sorted
    - promlinter               # Check Prometheus metrics naming via promlint
    - scopelint                # Deprecated: Scopelint checks for unpinned variables in go programs
    - tagliatelle              # Checks the struct tags.
    - wsl                      # Whitespace Linter - Forces you to use empty lines!
  enable:
    - asciicheck               # Simple linter to check that your code does not contain non-ASCII identifiers
    - bidichk                  # Checks for dangerous unicode character sequences
    - bodyclose                # checks whether HTTP response body is closed successfully
    - containedctx             # containedctx is a linter that detects struct contained context.Context field
    - contextcheck             # check the function whether use a non-inherited context
    - cyclop                   # checks function and package cyclomatic complexity
    - deadcode                 # Finds unused code
    - decorder                 # check declaration order and count of types, constants, variables and functions
    - depguard                 # Go linter that checks if package imports are in a list of acceptable packages
    - dogsled                  # Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f())
    - dupl                     # Tool for code clone detection
    - durationcheck            # check for two durations multiplied together
    - errcheck                 # Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases
    - errchkjson               # Checks types passed to the json encoding functions.
    - errname                  # Checks that sentinel errors are prefixed with the `Err` and error types are suffixed with the `Error`.
    - errorlint                # errorlint is a linter for that can be used to find code that will cause problems with the error wrapping scheme introduced in Go 1.13.
    - exhaustive               # check exhaustiveness of enum switch statements
    - exportloopref            # checks for pointers to enclosing loop variables
    - funlen                   # Tool for detection of long functions
    - gocognit                 # Computes and checks the cognitive complexity of functions
    - goconst                  # Finds repeated strings that could be replaced by a constant
    - gocritic                 # Provides diagnostics that check for bugs, performance and style issues.
    - gocyclo                  # Computes and checks the cyclomatic complexity of functions
    # - godot                    # Check if comments end in a period
    - gofmt                    # Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification
    - gofumpt                  # Gofumpt checks whether code was gofumpt-ed.
    - goimports                # In addition to fixing imports, goimports also formats your code in the same style as gofmt.
    - gomodguard               # Allow and block list linter for direct Go module dependencies.
    - goprintffuncname         # Checks that printf-like functions are named with `f` at the end
    - gosec                    # Inspects source code for security problems
    - gosimple                 # Linter for Go source code that specializes in simplifying a code
    - govet                    # Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - grouper                  # An analyzer to analyze expression groups.
    - ifshort                  # Checks that your code uses short syntax for if-statements whenever possible
    - importas                 # Enforces consistent import aliases
    - ineffassign              # Detects when assignments to existing variables are not used
    - ireturn                  # Accept Interfaces, Return Concrete Types
    - lll                      # Reports long lines
    - maintidx                 # maintidx measures the maintainability index of each function.
    - makezero                 # Finds slice declarations with non-zero initial length
    - misspell                 # Finds commonly misspelled English words in comments
    - nakedret                 # Finds naked returns in functions greater than a specified function length
    - nestif                   # Reports deeply nested if statements
    - nilerr                   # Finds the code that returns nil even if it checks that the error is not nil.
    - nilnil                   # Checks that there is no simultaneous return of `nil` error and an invalid value.
    - nlreturn                 # nlreturn checks for a new line before return and branch statements to increase code clarity
    - noctx                    # noctx finds sending http request without context.Context
    - nolintlint               # Reports ill-formed or insufficient nolint directives
    - paralleltest             # paralleltest detects missing usage of t.Parallel() method in your Go test
    - prealloc                 # Finds slice declarations that could potentially be preallocated
    - predeclared              # find code that shadows one of Go's predeclared identifiers
    - revive                   # Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint.
    - rowserrcheck             # checks whether Err of rows is checked successfully
    - sqlclosecheck            # Checks that sql.Rows and sql.Stmt are closed.
    - staticcheck              # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - structcheck              # Finds unused struct fields
    - stylecheck               # Stylecheck is a replacement for golint
    - tenv                     # tenv is analyzer that detects using os.Setenv instead of t.Setenv since Go1.17
    - testpackage              # linter that makes you use a separate _test package
    - thelper                  # thelper detects golang test helpers without t.Helper() call and checks the consistency of test helpers
    - tparallel                # tparallel detects inappropriate usage of t.Parallel() method in your Go test codes
    - typecheck                # Like the front-end of a Go compiler, parses and type-checks Go code
    - unconvert                # Remove unnecessary type conversions
    - unparam                  # Reports unused function parameters
    - unused                   # Checks Go code for unused constants, variables, functions and types
    - varcheck                 # Finds unused global variables and constants
    - varnamelen               # checks that the length of a variable's name matches its scope
    - wastedassign             # wastedassign finds wasted assignment statements.
    - whitespace               # Tool for detection of leading and trailing whitespace
    - wrapcheck                # Checks that errors returned from external packages are wrapped

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: true
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - funlen
        - gocognit
        - goconst
        - gocyclo
        - gosec
        - lll
        - wrapcheck
    - path: "(.*)?_example_test.go"
      linters:
        - gocritic
    # Exclude shadow checking on the variable named err
    - text: "shadow: declaration of \"err|ok\""
      linters:
        - govet
    - text: "continue with no blank line before"
      linters:
        - nlreturn
